name: minimized

on: [push]

jobs:
  read:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Reads Root Directory
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        id: dir
        with:
          directory: './'
